### ISSUE TITLE
How to apply side effect on an action ?

### ISSUE THREAD

**Issue by iamdey** [cr0cK/bouchon#7]
Here is my case: 

The inital API when receiving a new entity B will create automatically an A entity and link them using A.id.

I know it seems not possible to inject a redux middleware.  
May be redux-act can solves this ?

**Comment by cr0cK** [comment]
Hum first, be careful to not make a full relational DB with your JSON. Fixtures should be simple. Maybe you can save all your related data into one single JSON to avoid this "join".

But, if you really need, I think it's possible by using [multiple actions](https://github.com/cr0cK/bouchon#multiple-actions). You can dispatch actions of an another part of your fixtures. See [this example](https://github.com/cr0cK/bouchon#asynchronous-sample).

You can also use the `req` object to pass some data. Like [here](https://github.com/cr0cK/bouchon/blob/master/tests/0-readme-tutorials/async-articles/operations/index.js#L25) where I set an ID that I have computed, and [here](https://github.com/cr0cK/bouchon/blob/master/tests/0-readme-tutorials/async-articles/operations/index.js#L37) where I retrieve my ID to save it some seconds later.

Maybe you can trick like that by dispatching a backend action one millisecond later, to save the "join".

**Comment by iamdey** [comment]
Ok the `req.` trick does the job. Thanks.
